#SPDX-License-Identifier: MIT-0
---
# tasks file for firewall
- name: Install ufw
  become: true
  pacman:
    name: ufw

- name: Disable iptables service
  become: true
  systemd:
    name: iptables
    enabled: no
    state: stopped
  register: iptables

- name: Enable ufw service
  become: true
  when: iptables is succeeded
  systemd:
    name: ufw
    state: started
    enabled: yes

# TODO use community ufw module
- name: Firewall rules
  register: rule
  changed_when: rule.stdout.find("Skipping adding existing rule") != -1
  become: true
  shell: ufw "{{ item }}"
  loop:
    - default deny
    - allow from 192.168.0.0/24
    - limit ssh
