#SPDX-License-Identifier: MIT-0
---
# tasks file for network
- name: Install Network Managers
  become: true
  pacman:
    name:
      - networkmanager
      - networkmanager-openvpn
      - dhcpcd
      # - polkit

- name: Unwanted NetworkManagers
  become: true
  pacman:
    state: absent
    name:
      - iwd
      - netctl
      - systemd-networkd
      - connman
      - dhcpclient

- name: dhcpcd
  register: dhcpcd_nm_conf
  become: true
  blockinfile:
    create: true
    path: /etc/NetworkManager/conf.d/dhcpcd.conf
    block: |
      [main]
      dhcp=dhcpcd

# - name: remove dhcpcd
#   become: true
#   file:
#     state: absent
#     path: /etc/NetworkManager/conf.d/dhcpcd.conf

- name: Enable NetworkManager
  become: true
  systemd:
    name: NetworkManager
    state: started
    enabled: yes

- name: Reload NetworkManager
  when: dhcpcd_nm_conf is changed
  systemd:
    name: NetworkManager
    state: reloaded

# TODO
# - name: Eduroam
