#SPDX-License-Identifier: MIT-0
---
# tasks file for network
- name: Install Network Managers
  become: true
  pacman:
    name:
      - networkmanager
      - networkmanager-openvpn
      # - polkit
- name: Unwanted NetworkManagers
  become: true
  pacman:
    state: absent
    name:
      - iwd
      - netctl
      - systemd-networkd
      - dhcpcd
      - connman
      - dhcpclient

# - name: dhcpcd
#   become: true
#   blockinfile:
#     create: true
#     path: /etc/NetworkManager/conf.d/dhcpcd.conf
#     block: |
#       [main]
#       dhcp=dhcpcd

- name: remove dhcpcd
  become: true
  file:
    state: absent
    path: /etc/NetworkManager/conf.d/dhcpcd.conf

- name: Enable NetworkManager
  become: true
  systemd:
    name: NetworkManager
    state: started
    enabled: yes

# TODO
# - name: Eduroam
