#SPDX-License-Identifier: MIT-0
---
# tasks file for a1111
- name: Dependencies
  become: true
  pacman:
    name: 
      - wget
      - git
      - python

    # TODO WHEN
- name: paru dep
  shell: paru -S python311 --needed --noconfirm

  # TODO 
  # VENV --> pyhton3.11 ensurepip --upgrade --> pyhthon3.11 -m pip install .,..
# - name: pipx deps
#   shell: pipx install torch torchvision --include-deps
#   register: pipx
#
# - name: resolve pipx errors
#   when: pipx is failed
#   shell: pipx install torch torchvision --include-deps --force

# python3 -m venv venv/


- name: Clone Git Repo
  git:
    update: no
    repo: "https://github.com/AUTOMATIC1111/stable-diffusion-webui"
    dest: "{{ homedir }}/Projects/private/a1111"
