- name: Install KeyD
  become: true
  pacman:
    name: keyd

- name: KeyD Config
  become: true
  copy:
    src: "{{ role_path }}/files/keyd.conf"
    dest: "/etc/keyd/default.conf"
  register: keyd_config

- name: Enable KeyD
  become: true
  systemd:
    state: started
    enabled: yes
    name: keyd

- name: Reload KeyD
  when: keyd_config is changed
  become: true
  command:
    argv:
      - keyd
      - reload
