#SPDX-License-Identifier: MIT-0
---
# tasks file for userspace
- name: Remove Unwanted Apps
  become: true
  pacman:
    state: absent
    name:
      - rust
      - alacritty

- name: Install Pacman Apps
  become: true
  pacman:
    name:
      - btop
      - cheese
      - docker
      - docker-compose
      - firefox
      - fzf
      - git-delta
      - go
      - kdeconnect
      - keepassxc
      - kitty
      - kwalletmanager
      - lolcat
      - man-db 
      - man-pages
      - nextcloud-client
      - nnn
      - openvpn
      - pavucontrol
      - playerctl
      - rustup
      - signal-desktop
      - sl
      - tldr
      - tmux
      - vlc # Flatpak ?
      - zoxide
      - zsh

- name: SimLink Vi -> NVIM
  become: true
  file:
    src: /bin/nvim
    dest: "{{ item }}"
    state: link
  loop:
    - /bin/vi
    - /bin/vim

- name: Install AUR Apps
  shell: paru --noconfirm --needed -S oh-my-posh-bin mullvad-vpn-bin
  register: paru_output
  changed_when: paru_output.stderr.find('up to date -- skipping') == -1

- name: Add the flathub user beta repo
  become: true
  community.general.flatpak_remote:
    name: flathub-beta
    state: present
    flatpakrepo_url: https://flathub.org/beta-repo/flathub-beta.flatpakrepo
    method: system

- name: Install Flatpak Apps
  become: true
  flatpak:
    name:
      - com.discordapp.Discord
      - com.jetbrains.GoLand
      - com.jetbrains.IntelliJ-IDEA-Ultimate
      - md.obsidian.Obsidian
      - org.audacityteam.Audacity
      - org.libreoffice.LibreOffice
      - org.mozilla.Thunderbird
      - chat.revolt.RevoltDesktop

- name: Install Flatpak Beta Apps
  become: true
  flatpak:
    remote: flathub-beta
    method: system
    name: com.discordapp.DiscordCanary

- name: KeyD
  import_tasks: keyd.yml

- name: Thunderbird
  import_tasks: thunderbird.yml
