#SPDX-License-Identifier: MIT-0
---
# tasks file for hyprland
# Configure Hyprland
# - name: Ensure Dotfiles
#   import_tasks: dotfiles.yml
# - name: Ensure AUR
#   import_tasks: aur.yml

- name: Install Hyprland and Plugins
  become: true
  pacman:
    name:
      - hyprland
      - hypridle
      - hyprlock
      - hyprsunset
    state: latest

- name: Copy hyprsunset job
  copy:
    src: "{{ role_path }}/files/hyprsunset.sh"
    dest: "{{ homedir }}/.local/cron/hyprsunset.sh"
    mode: '0755'
    owner: "{{ username }}"


- name: hyprsunset cronjob
  cron:
    name: hyprsunset
    user: "{{ username }}"
    hour: "16-23"
    minute: "*/20"
    job: "{{ homedir }}/.local/cron/hyprsunset.sh 1000"

- name: screenshot
  become: true
  pacman:
    name:
      - slurp
      - wl-clipboard
      - grim

- name: waybar
  become: true
  pacman: 
    name: waybar

- name: notification
  become: true
  pacman:
    name: 
      # - polkit # TODO What is this
      - mako

- name: xdg-desktop
  become: true
  pacman:
    name:
      - xdg-desktop-portal
      - xdg-desktop-portal-hyprland
      - xdg-desktop-portal-gtk
    state: latest

- name: background
  become: true
  pacman:
    name:
      - swww
# TODO Cron job using swww query | grep 'color' swww img ...

# TODO Abstrace background image (dir under home?)
- name: Copy Irithyll Background
  copy:
    src: "{{ homedir }}/Pictures/irithyll.jpg"
    dest: "{{ homedir }}/Pictures/irithyll.jpg"
  register: copy_bg

- name: tofi (Programm runner)
  shell: paru -S tofi --needed --noconfirm
  register: paru_output
  changed_when: paru_output.stderr.find('up to date -- skipping') == -1
