---
# TODO both pcs in one file
- name: Setup Laptop
  hosts: laptop
  roles:
    - common-setup
    - usb-c-thunderbolt
    - virtualization
    - powermanagment
    - bluetooth

  tasks:
    # For hotfixes
    # - name: Check for Updates
    #   import_tasks: check_for_updates.yml
