---
- name: Setup PC
  hosts: self
  roles:
    - common-setup
    - gaming
    - virtualization
    - bluetooth
# TEST
  tasks:
    - name: Check for Updates
      import_tasks: check_for_updates.yml
