---
- name: Setup Laptop
  hosts: self
  roles:
    - common-setup
    - usb-c-thunderbolt
    - gaming
    - bluetooth

  tasks:
    - name: Check for Updates
      import_tasks: check_for_updates.yml
