- name: VM Test
  hosts: vm
  roles:
    - common-setup 
    - powermanagment
    - gaming
    - bluetooth

  tasks:
    - name: Disable KeyD
      become: true
      systemd:
        name: keyd
        state: stopped
        enabled: no
      changed_when: false
    
    - name: Historical
      import_tasks: historical.yml
