#SPDX-License-Identifier: MIT-0
---
# tasks file for bootloader
- name: Install Grub
  become: true
  pacman:
    name:
      - grub
      - efibootmgr
      - os-prober

- name: Check for Catppuccin Grub Theme
  become: true
  check_mode: true
  file:
    state: directory
    path: '/boot/grub/themes/catppuccin-mocha-grub-theme/'
  failed_when: false
  register: found_catppuccin

- name: Download Catppuccin Grub Theme
  when: found_catppuccin is changed
  become: true
  git:
    repo: https://github.com/catppuccin/grub.git
    dest: /tmp/grub-catppuccin
    clone: yes
    depth: 1
  register: catppuccin_clone

- name: Install Catppuccin Grub Theme
  when: catppuccin_clone is succeeded and found_catppuccin is changed
  become: true
  copy:
    remote_src: true
    src: /tmp/grub-catppuccin/src/catppuccin-mocha-grub-theme/
    dest: /boot/grub/themes/catppuccin-mocha-grub-theme/
  register: catppuccin_fresh_install

- name: Catppuccin CleanUP
  when: catppuccin_clone is not skipped 
  become: true
  file:
    state: absent
    path: /tmp/grub-catppuccin

- name: Grub Console
  become: true
  lineinfile: 
    path: /etc/default/grub
    state: present
    regexp: '^GRUB_TERMINAL_INPUT=console$'
    line: '# GRUB_TERMINAL_INPUT=console'
  register: changed_ter_input

- name: Grub Theme
  become: true
  lineinfile: 
    path: /etc/default/grub
    state: present
    regexp: '^GRUB_THEME='
    line: GRUB_THEME="/boot/grub/themes/catppuccin-mocha-grub-theme/theme.txt"
  register: installed_theme

- name: OS-Prober
  become: true
  lineinfile:
    state: absent
    path: /etc/default/grub
    line: GRUB_DISABLE_OS_PROBER=false
    insertafter: ^#GRUB_DISABLE_OS_PROBER=false$
  register: os_prober

- name: Update Grub Config
  become: true
  when: os_prober is changed or installed_theme is changed or changed_ter_input is changed or catppuccin_fresh_install is changed
  command:
    argv:
      - grub-mkconfig
      - -o
      - /boot/grub/grub.cfg
