#SPDX-License-Identifier: MIT-0
---
# tasks file for dotfiles
- name: Install Stow
  become: true
  package:
    name: stow
  register: stow

- name: Check for and or Download Dotfiles
  git:
    repo: git@github.com:Lars5Janssen/dotfiles.git
    dest: ~/dotfiles/
    update: no

- name: Stow Dotfiles
  when: stow is succeeded
  command:
    chdir: ~/dotfiles/
    cmd: stow . -v
  register: result
  changed_when: result.stdout.find('LINK') != -1
  failed_when: result.rc != 0

# TODO Cron Job that reminds of Unsaved Changes
- name: Ensure Notify Send
  pacman:
    name: libnotify
    
- name: Create Cron Script
  register: script
  blockinfile:
    path: ~/.local/cron/dotfiles_cron_job.sh
    create: true
    mode: '0755'
    block: |
      #!/bin/bash
      cd ~/dotfiles/
      UNCOMMITED_CHANGES="$(git diff-index HEAD --)"
      UNPUSHED_COMMITS="$(git push --dry-run)"

      if [[ "$UNCOMMITED_CHANGES" != "" ]]; then
          notify-send "You have uncommited changes in your dotfiles"
      fi

      if [[ "$UNPUSHED_COMMITS" != "Everything up-to-date" ]]; then
          notify-send "You have unpushed commits in your dotfiles"
      fi

- name: Cron Reminder
  cron:
    name: dotfiles reminder
    hour: "*"
    user: l
    job: ~/.local/cron/dotfiles_cron_job.sh
