#SPDX-License-Identifier: MIT-0
---
# tasks file for dotfiles
- name: Install Stow
  become: true
  package:
    name: stow

- name: Check for and or Download Dotfiles
  register: stow
  git:
    repo: git@github.com:Lars5Janssen/dotfiles.git
    dest: "{{ homedir }}/dotfiles/"
    update: no

- name: Stow Dotfiles
  when: stow is changed
  command:
    chdir: "{{ homedir }}/dotfiles/"
    cmd: stow --dotfiles . -v 
  register: result
  changed_when: result.stdout.find('LINK') != -1
  failed_when: result.rc != 0

- name: Git Repo Check Notification for Dotfiles
  cron:
    name: dotfiles reminder
    minute: "*/10"
    user: "{{ username }}"
    job: "nice {{ homedir }}/.local/cron/git_repo_check_cron.sh {{ homedir }}/dotfiles/ 10000"

- name: Btop
  import_tasks: btop.yml
