#SPDX-License-Identifier: MIT-0
---
# tasks file for dotfiles
- name: Install Stow
  become: true
  package:
    name: stow
  register: stow

- name: Check for and or Download Dotfiles
  git:
    repo: git@github.com:Lars5Janssen/dotfiles.git
    dest: "/home/{{ username }}/dotfiles/"
    update: no

- name: Stow Dotfiles
  when: stow is succeeded
  command:
    chdir: "/home/{{ username }}/dotfiles/"
    cmd: stow . -v
  register: result
  changed_when: result.stdout.find('LINK') != -1
  failed_when: result.rc != 0

- name: Cron Reminder
  cron:
    name: dotfiles reminder
    minute: "*/10"
    user: "{{ username }}"
    job: "/home/{{ username }}/.local/cron/git_repo_check_cron.sh /home/{{ username }}/dotfiles/ 600000"
