#SPDX-License-Identifier: MIT-0
---
# tasks file for cron
- name: Install cronie
  become: true
  pacman:
    name: cronie

- name: Install Notify send (For scripts)
  become: true
  pacman:
    name: libnotify

# TODO LOG CLEANUP SCRIPT
- name: Place Git Repo check script
  copy:
    src: "{{ role_path }}/files/git_repo_check_cron.sh"
    dest: "{{ homedir }}/.local/cron/git_repo_check_cron.sh"
    owner: "{{ username }}"
    mode: '0755'

- name: Enable Cronie 
  become: true
  systemd:
    name: cronie
    enabled: yes
    state: started

- name: Anacron dirs
  file:
    path: "{{ homedir }}/{{ item }}"
    state: directory
    owner: "{{ username }}"
  loop:
    - ".local/etc/"
    - ".local/etc/cron.daily/"
    - ".local/etc/cron.weekly/"
    - ".local/etc/cron.monthly/"
    - ".local/var/spool/anacron/"

- name: Anacron file
  blockinfile:
    path: "{{ homedir }}/.local/etc/anacrontab"
    create: true
    block: |
      # /etc/anacrontab: configuration file for anacron

      # See anacron(8) and anacrontab(5) for details.

      SHELL=/bin/sh
      PATH=/sbin:/bin:/usr/sbin:/usr/bin
      MAILTO=root
      # the maximal random delay added to the base delay of the jobs
      RANDOM_DELAY=45
      # the jobs will be started during the following hours only
      START_HOURS_RANGE=3-22

      #period in days delay in minutes  job-identifier  command
      1               5                 cron.daily      nice find {{ homedir }}/.local/etc/cron.daily/* -prune -type f -executable -exec {} \;
      7               25                cron.weekly     nice find {{ homedir }}/.local/etc/cron.weekly/* -prune -type f -executable -exec {} \;
      @monthly        45                cron.monthly    nice find {{ homedir }}/.local/etc/cron.monthly/* -prune -type f -executable -exec {} \;
  # copy:
  #   src: "{{ role_path }}/files/anacrontab"
  #   dest: "{{ homedir }}/.local/etc/anacrontab"
  #   owner: "{{ username }}"

- name: Anacron cron job
  cron:
    name: Anacron
    minute: "0"
    job: "/usr/sbin/anacron -s -t {{ homedir }}/.local/etc/anacrontab -S {{ homedir }}/.local/var/spool/anacron"
