#SPDX-License-Identifier: MIT-0
---
# tasks file for a1111
- name: Dependencies
  become: true
  pacman:
    name: 
      - wget
      - git
      - python

- name: dep
  shell: paru -S python311 --needed --noconfirm

# python3 -m venv venv/


- name: Clone Git Repo
  git:
    update: no
    repo: "https://github.com/AUTOMATIC1111/stable-diffusion-webui"
    dest: "{{ homedir }}/Projects/private/a1111"
