#SPDX-License-Identifier: MIT-0
---
# tasks file for self-preservation
- name: Install ansible
  become: true
  pacman:
    name: ansible

- name: Check for and or Download Ansible Repo
  become_user: "{{ username }}"
  git:
    repo: git@github.com:Lars5Janssen/ansible_arch_linux.git
    dest: "{{ homedir }}/Projects/private/ansible/"
    update: no

- name: self-preservation cron job
  cron:
    name: ansible_arch_linux reminder
    minute: "*/10"
    user: "{{ username }}"
    job: "nice {{ homedir }}/.local/cron/git_repo_check_cron.sh {{ homedir }}/Projects/private/ansible/ 10000"
