#SPDX-License-Identifier: MIT-0
---
# tasks file for dotfiles
- name: Install Stow
  become: true
  package:
    name: stow

- name: Check for and or Download Dotfiles
  register: stow
  git:
    repo: git@github.com:Lars5Janssen/dotfiles.git
    accept_newhostkey: true
    dest: "{{ homedir }}/dotfiles/"
    update: no

- name: Delete old config files
  when: stow is changed
  file:
    path: "{{ homedir }}/{{ item }}"
    state: absent
  loop:
    - .bashrc
    - .config/hypr

- name: Ensure Directories
  file:
    path: "{{ homedir }}/{{ item }}"
    state: directory
  loop:
    - .local
    - ./local/share
    - ./local/share/hyprland
    - ./local/share/nvim
    - ./local/share/zinit
    - ./local/share/zoxide
    - .config/
    - .config/kdeconnect
    - .config/go/telemetry

- name: Stow Dotfiles
  when: stow is changed
  command:
    chdir: "{{ homedir }}/dotfiles/"
    cmd: stow --dotfiles . -v 
  register: result
  changed_when: result.stdout.find('LINK') != -1
  failed_when: result.rc != 0

- name: Git Repo Check Notification for Dotfiles
  cron:
    name: dotfiles reminder
    minute: "*/10"
    user: "{{ username }}"
    job: "nice {{ homedir }}/.local/cron/git_repo_check_cron.sh {{ homedir }}/dotfiles/ 10000"


- name: rust default
  shell: rustup default stable

- name: scriptisto
  shell: paru -S scriptisto 

- name: Btop
  import_tasks: btop.yml
