#SPDX-License-Identifier: MIT-0
---
# tasks file for bluetooth
- name: Install bluetooth utilities
  become: true
  pacman:
    name:
      - bluez
      - bluez-utils
      - bluetui
      - blueman

- name: Enable bluetooth service
  become: true
  systemd:
    name: bluetooth
    # state: started
    enabled: yes
