#SPDX-License-Identifier: MIT-0
---
# tasks file for ssh
# - name: ssh_port
#   import_tasks: ssh_port.yml

- name: openssh installed
  pacman:
    name: openssh

- name: copy ssh key from current user
  become: true
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_ed25519.pub') }}"

- name: sshd config
  become: true
  copy:
    src: "{{ role_path }}/files/sshd_config"
    dest: "/etc/ssh/sshd_config"
    owner: "{{ rootusername }}"
  register: sshd_config
