#SPDX-License-Identifier: MIT-0
---
# tasks file for user
# TODO MAKE SHURE USER IS PRESENT
- name: Ensure User
  check_mode: true
  user:
    name: "{{ username }}"
    groups: wheel
    shell: /bin/zsh
    # TODO SSH KEY???
    append: true 

- name: Projects dir
  file:
    state: directory
    path: "/home/{{ username }}/Projects"
    owner: "{{ username }}"

# TODO GIT
