#SPDX-License-Identifier: MIT-0
---
# tasks file for userspace
- name: Install Pacman Apps
  become: true
  pacman:
    name:
      - tldr
      - sl
      - kitty
      - vlc # Flatpak ?
      - lolcat
      - nextcloud-client
      - man-db 
      - man-pages
      - keepassxc
      - firefox
      - kdeconnect
      - cheese
      # These Programms might be better in a diffrent playbook 
      # or refactored out of general userspace
      - btop
      - docker
      - docker-compose
      - playerctl
      - pavucontrol
      - rustup
      - go
      - zoxide
      - zsh
      - fzf
      - openvpn

- name: Unwanted Pacman Apps
  become: true
  pacman:
    state: absent
    name:
      - alacritty

- name: Install AUR Apps
  command:
    argv:
      - paru 
      - --noconfirm 
      - --needed
      - -S
      - oh-my-posh-bin 
      - mullvad-vpn-bin
  register: paru_output
  changed_when: paru_output.stderr.find('up to date -- skipping') == -1

- name: Install Flatpak Apps
  become_user: "{{ username }}"
  flatpak:
    # method: user
    name:
      - com.discordapp.Discord
      - com.jetbrains.GoLand
      - com.jetbrains.IntelliJ-IDEA-Ultimate
      - md.obsidian.Obsidian
      - org.audacityteam.Audacity
      - org.libreoffice.LibreOffice
      - org.mozilla.Thunderbird
      - chat.revolt.RevoltDesktop

- name: Install Flatpak Beta Apps
  flatpak:
    remote: flathub-beta
    method: system
    name: com.discordapp.DiscordCanary


# TODO Refactor KeyD into own roll
- name: Install KeyD
  pacman:
    name: keyd

- name: KeyD Config
  copy:
    src: "{{ role_path }}/files/keyd.conf"
    dest: "/etc/keyd/default.conf"
  register: keyd_config

- name: Enable KeyD
  systemd:
    state: started
    enabled: yes
    name: keyd

- name: Reload KeyD
  when: keyd_config is changed
  become: true
  command:
    argv:
      - keyd
      - reload
