---
- name: Check for Intel CPU
  register: intel
  shell: cat /proc/cpuinfo | grep 'vendor' | uniq | sed 's/:/=/' 
  changed_when: false

# TODO
- name: Check for AMD
  register: amd
  debug: 
    msg: TODO

- name: Check for not both
  when: 
    - ansible_facts['processor'][1].find("Intel") != -1
    - false # TODO AMD
  debug:
    msg: Detected Both AMD and Intel CPU --> DANGER
  failed_when: true

#######################
###      INTEL      ###
#######################

- name: Install Intell Microcode
  when: ansible_facts['processor'][1].find("Intel") != -1
  become: true
  pacman:
    name: intel-ucode

- name: Remove Intell Microcode
  when: not ansible_facts['processor'][1].find("Intel") != -1
  become: true
  pacman:
    state: absent
    name: intel-ucode

#######################
###       AMD       ###
#######################

- name: Install AMD microcode
  when: false
  become: true
  pacman:
    name: amd-ucode

- name: Remove AMD microcode
  when: true
  become: true
  pacman:
    name: amd-ucode
    state: absent
