---
- name: Check for not both
  when: 
    - ansible_facts['processor'][1].find("Intel") != -1
    - ansible_facts['processor'][1].find("AuthenticAMD") != -1
  debug:
    msg: Detected Both AMD and Intel CPU --> DANGER
  failed_when: true

#######################
###      INTEL      ###
#######################

- name: Install Intell Microcode
  when: ansible_facts['processor'][1].find("Intel") != -1
  become: true
  pacman:
    name: intel-ucode

- name: Remove Intell Microcode
  when: ansible_facts['processor'][1].find("Intel") == -1
  become: true
  pacman:
    state: absent
    name: intel-ucode

#######################
###       AMD       ###
#######################

- name: Install AMD microcode
  when: ansible_facts['processor'][1].find("AuthenticAMD") != -1
  become: true
  pacman:
    name: amd-ucode

- name: Remove AMD microcode
  when: ansible_facts['processor'][1].find("AuthenticAMD") == -1
  become: true
  pacman:
    name: amd-ucode
    state: absent
