---
- name: Check for Intel CPU
  register: intel
  shell: cat /proc/cpuinfo | grep 'vendor' | uniq | sed 's/:/=/' 
  changed_when: false

# TODO REFACTOR MULTILIB SUPPORT
- name: Check for 32 Bit Support
  blockinfile:
    path: /etc/pacman.conf
    state: present
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist
  check_mode: true
  register: multilib_support

# TODO REMOVE DUPLICATION FOR ALL 
- name: Install Intell Drivers
  when: intel.stdout.find('vendor_id	= GenuineIntel') != -1
  become: true
  pacman:
    name: 
      - intel-ucode
      - vulkan-intel

- name: Install Intell 32 Bit Drivers
  when: multilib_support is succeeded and intel.stdout.find('vendor_id	= GenuineIntel') != -1
  become: true
  pacman:
    name: lib32-vulkan-intel

- name: Remove Intell Drivers
  become: true
  when: intel.stdout.find('vendor_id	= GenuineIntel') == -1
  # when: false
  pacman:
    state: absent
    name: 
      - intel-ucode
      - vulkan-intel
      - lib32-vulkan-intel
