#SPDX-License-Identifier: MIT-0
---
# tasks file for flatpak
- name: Install Flatpak
  pacman:
    name: flatpak

- name: Flatseal
  flatpak:
    name: com.github.tchx84.Flatseal

# TODO XDG Desktop Portal Config
