#SPDX-License-Identifier: MIT-0
---
# tasks file for pacman
- name: Misc Pacman Config Options
  become: true
  lineinfile:
    path: /etc/pacman.conf
    state: "{{ item.state }}"
    line: "{{ item.option }}"
    insertafter: ^\[options\]$
  loop:
    - { option: Color, state: present}
    - { option: ILoveCandy, state: present}
    - { option: ParallelDownloads = 8, state: present}

- name: 32 Bit Support 
  become: true
  blockinfile:
    path: /etc/pacman.conf
    state: present
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist
    insertafter: ^#\[multilib\]$
  register: multilib

- name: Sync databse
  when: multilib is changed
  become: true
  pacman:
    update_cache: yes

- name: Copy Pacman cron job
  copy:
    src: "{{ role_path }}/files/pacman_update_checker.sh"
    dest: "{{ homedir }}/.local/etc/cron.daily/pacman_update_checker.sh"
    owner: "{{ username }}"
    mode: '0755'

- name: Pacman Cron Job
  cron:
    name: "Pacman Reminder"
    hour: "*/3"
    user: "{{ username }}"
    job: "nice {{ homedir }}/.local/etc/cron.daily/pacman_update_checker.sh delay"

- name: Install Relector
  become: true
  pacman:
    name: reflector
    state: present
  register: reflector

- name: Use Reflector
  become: true
  cron:
    name: "Pacman Reflector"
    hour: "*/6"
    user: "{{ rootusername }}"
    job: nice reflector --country Germany --sort rate --protocol https --save /etc/pacman.d/mirrorlist
    # TODO move to anacron and add logs
