#SPDX-License-Identifier: MIT-0
---
# tasks file for pacman
- name: Misc Pacman Config Options
  lineinfile:
    path: /etc/pacman.conf
    state: "{{ item.state }}"
    line: "{{ item.option }}"
  loop:
    - { option: Color, state: present}
    - { option: ILoveCandy, state: present}
    - { option: ParallelDownloads = 8, state: present}

- name: 32-Bit (Multilib)
  become: true
  blockinfile:
    path: /etc/pacman.conf
    state: present
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist

- name: Install Relector
  become: true
  pacman:
    name: reflector
    state: present
  register: reflector

- name: Use Reflector
  cron:
    name: "Pacman Reflector"
    special_time: weekly
    job: reflector --country Germany --sort rate --protocol https --save /etc/pacman.d/mirrorlist
