#SPDX-License-Identifier: MIT-0
---
# tasks file for pacman
- name: Color
  lineinfile:
    path: /etc/pacman.conf
    state: present
    line: Color

- name: I Love Candy (Pacman easter egg)
  lineinfile:
    path: /etc/pacman.conf
    state: present
    line: ILoveCandy 

- name: 32-Bit (Multilib)
  become: true
  blockinfile:
    path: /etc/pacman.conf
    state: present
    block: |
      \[multilib\]
      Include = /etc/pacman.d/mirrorlist

- name: download threads
  lineinfile:
    path: /etc/pacman.conf
    state: present
    line: ParallelDownloads = 8

- name: Install Relector
  become: true
  pacman:
    name: reflector
    state: present
  register: reflector

# Make Use of Reflector A Cron Job
- name: Use Reflector
  debug:
    msg: Make Use of Reflector a Cron Job
#   when: reflector is succeeded
#   become: true
#   command:
#     argv:
#       - reflector
#       - --country 
#       - Germany
#       - --sort
#       - rate
#       - --protocol
#       - https
#       - --save
#       - /etc/pacman.d/mirrorlist
