#SPDX-License-Identifier: MIT-0
---
# tasks file for pacman
- name: Copy Pacman Conf
  become: true
  copy:
    src: "{{ role_path }}/files/pacman.conf"
    dest: "/etc/pacman.conf"
    owner: "{{ rootusername }}"
  register: conf

- name: Sync databse
  when: conf is changed
  become: true
  pacman:
    update_cache: yes

- name: Copy Pacman cron job
  copy:
    src: "{{ role_path }}/files/pacman_update_checker.sh"
    dest: "{{ homedir }}/.local/etc/cron.daily/pacman_update_checker.sh"
    owner: "{{ username }}"
    mode: '0755'

- name: Pacman Cron Job
  cron:
    name: "Pacman Reminder"
    hour: "*/3"
    minute: "0,30"
    user: "{{ username }}"
    job: "nice {{ homedir }}/.local/etc/cron.daily/pacman_update_checker.sh delay"

- name: Install Relector
  become: true
  pacman:
    name: reflector
    state: present
  register: reflector

- name: Use Reflector
  become: true
  cron:
    name: "Pacman Reflector"
    hour: "*/6"
    user: "{{ rootusername }}"
    job: nice reflector --country Germany --sort rate --protocol https --save /etc/pacman.d/mirrorlist
    # TODO move to anacron and add logs

- name: Run reflector
  when: reflector is changed
  become: true
  shell: reflector --country Germany --sort rate --protocol https --save /etc/pacman.d/mirrorlist
  failed_when: false
