#SPDX-License-Identifier: MIT-0
---
# tasks file for aur
- name: Check if Paru is installed
  command:
    cmd: which paru
  register: paru_installed
  ignore_errors: true
  changed_when: false

- name: Install Base Devel
  when: paru_installed.rc != 0
  become: true
  pacman:
    name: base-devel

- name: Download Paru
  when: paru_installed.rc != 0
  become_user: "{{ username }}"
  git:
    repo: 'https://aur.archlinux.org/paru.git'
    dest: "/home/{{ username }}"
  register: clone_result

- name: Install Paru
  when: paru_installed.rc != 0 and clone_result is succeeded
  become: true
  command:
    chdir: "/home/{{ username }}/paru/"
    argv:
      - makepkg
      - -si

- name: Ensure Paru CleanUp
  when: paru_installed.rc != 0
  file:
    state: absent
    path: "/home/{{ username }}/paru/"
