#SPDX-License-Identifier: MIT-0
---
# tasks file for aur
- name: Check if Paru is installed
  command:
    cmd: which paru
  register: paru_installed
  ignore_errors: true
  changed_when: false
  failed_when: false

- name: Install Base Devel
  become: true
  pacman:
    name: base-devel

- name: Download Paru
  when: paru_installed.rc != 0
  become_user: "{{ username }}"
  git:
    repo: 'https://aur.archlinux.org/paru.git'
    dest: "{{ homedir }}/paru/"
  register: clone_result

- name: Remove Sudo PW Check
  when: paru_installed.rc != 0 and clone_result is succeeded
  become: true
  community.general.sudoers:
    name: allow makepkg
    user: "{{ username }}"
    commands: /usr/bin/pacman
    state: present

- name: Install Paru
  when: paru_installed.rc != 0 and clone_result is succeeded
  become_user: "{{ username }}"
  command:
    chdir: "{{ homedir }}/paru/"
    argv:
      - makepkg
      - -si
      - --noconfirm

- name: Reenable Sudo PW Check
  become: true
  community.general.sudoers:
    name: allow makepkg
    user: "{{ username }}"
    commands: /usr/bin/pacman
    state: absent

- name: Ensure Paru CleanUp
  when: paru_installed.rc != 0
  file:
    state: absent
    path: "{{ homedir }}/paru/"
