#SPDX-License-Identifier: MIT-0
---
# tasks file for nvim
- name: Install nvim and direct dependencies
  become: true
  pacman: # These package names are arch specific no guarantee for other distros
    name:
      - neovim
      - lua
      - luarocks

- name: Install language servers
  become: true
  pacman:
    name:
      - bash-language-server
      - jedi-language-server
      - lua-language-server
      - vscode-json-languageserver
      - yaml-language-server
      - tree-sitter
      # might add tree-siiter
      #                      -bash
      #                      -c
      #                      -lua
      #                      -markdown
      #                      -rust
      #                      -vim
      #                      -vimdoc
      #                      -python

- name: Install AUR Server
  shell: paru -S dockerfile-language-server-bin --noconfirm --needed
  register: paru_output
  changed_when: paru_output.stderr.find('up to date -- skipping') == -1
