#SPDX-License-Identifier: MIT-0
---
# tasks file for pacman
- name: Copy Pacman Conf
  become: true
  copy:
    src: "{{ role_path }}/files/pacman.conf"
    dest: "/etc/pacman.conf"
    owner: "{{ rootusername }}"
  register: conf

- name: Sync databse
  when: conf is changed
  become: true
  pacman:
    update_cache: yes

- name: Install Relector
  become: true
  pacman:
    name: reflector
    state: present
  register: reflector

- name: Reflector Config
  become: true
  copy:
    src: "{{ role_path }}/files/reflector.conf"
    dest: /etc/xdg/reflector/reflector.conf
    owner: "{{ rootusername }}"

- name: Enable Reflector Service
  become: true
  systemd:
    name: reflector.service
    state: started
    enabled: yes

- name: Run reflector
  when: reflector is changed
  become: true
  shell: reflector --country Germany --sort rate --protocol https --save /etc/pacman.d/mirrorlist
  failed_when: false
