#SPDX-License-Identifier: MIT-0
---
# tasks file for wake-on-lan
- name: install ethtool
  become: true
  pacman:
    name: ethtool


- name: Copy wake-on-lan systemd job
  become: true
  copy:
    src: "{{ role_path }}/files/wol@.service"
    dest: "/etc/systemd/system/wol@.service"
    owner: "{{ rootusername }}"

- name: activate wake-on-lan
  become: true
  systemd:
    name: "wol@{{ ansible_facts['default_ipv4']['interface'] }}.service"
    enabled: yes

