#SPDX-License-Identifier: MIT-0
---
# tasks file for login-manager
# For Custom Login on TTY
- name: Install GreetD
  become: true
  pacman:
    name: 
      - greetd
      - greetd-agreety
      - zsh

# TODO INSTA LOGIN ON PC

# Find a way to check for this config

- name: Check greetD Config
  register: greetd_config
  become: true
  blockinfile:
    path: /etc/greetd/config.toml
    block: |
      [terminal]
      # The VT to run the greeter on. Can be "next", "current" or a number
      # designating the VT.
      vt = 1

      # The default session, also known as the greeter.
      [initial_session]
      command = "zsh"
      user = "{{ username }}"

      [default_session]

      # `agreety` is the bundled agetty/login-lookalike. You can replace `/bin/sh`
      # with whatever you want started, such as `sway`.
      command = "agreety --cmd /bin/zsh"

      # The user to run the command as. The privileges this user must have depends
      # on the greeter. A graphical greeter may for example require the user to be
      # in the `video` group.
      user = "greeter"

# - name: Disable sddm
#   when: greetd_config is succeeded # TODO or ()
#   become: true
#   systemd:
#     name: sddm
#     state: stopped
#     enabled: no

- name: Enable greetD
  when: greetd_config is succeeded # TODO or ()
  become: true
  systemd:
    name: greetd
    # state: started
    enabled: yes
