---
# TODO IS 32 Bit support used right multilib_support is succeeded and ... is changed???
- name: install lshw
  become: true
  pacman:
    name: lshw

- name: Check for Card vendor
  become: true
  shell: lshw -class display | grep vendor
  changed_when: false
  register: vendor

- name: Check for not both
  when: 
    - vendor.stdout.find("NVIDIA") != -1
    - vendor.stdout.find("Intel") != -1
  debug:
    msg: Found both Nvidia GPU and Intel CPU --> DANGER
  failed_when: true

- name: Check for 32 Bit Support
  blockinfile:
    path: /etc/pacman.conf
    state: present
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist
  check_mode: true
  register: multilib_support

#######################
###      REMOVE     ###
#######################

###      NVIDIA     ###
- name: Remove Nivdia 32 Bit drivers
  when: not multilib_support is succeeded or vendor.stdout.find("NVIDIA") == -1 # TODO OR NOT NVIDIA is succeeded
  become: true
  pacman:
    state: absent
    name: lib32-nvidia-utils


- name: Remove Nivdia drivers and etc
  when: not vendor.stdout.find("NVIDIA") != -1
  become: true
  pacman:
    state: absent
    name: nivida

- name: Remove Nivdia 32 Bit drivers
  when: multilib_support is not succeeded or vendor.stdout.find("NVIDIA") == -1 # TODO OR NOT NVIDIA is succeeded
  become: true
  pacman:
    state: absent
    name: lib32-nvidia-utils

###      INTEL      ###
- name: Remove Intel Driver
  when: vendor.stdout.find("Intel") == -1
  become: true
  pacman:
    state: absent
    name: vulkan-intel

- name: Remove Intel 32 Bit Driver
  when: vendor.stdout.find("Intel") == -1 or multilib_support is not succeeded
  become: true
  pacman:
    state: absent
    name: lib32-vulkan-intel

#######################
###     INSTALL     ###
#######################

###      NVIDIA     ###
- name: Install Nivdia drivers and etc
  when: vendor.stdout.find("NVIDIA") != -1
  become: true
  pacman:
    name: nvidia

- name: Install Nivdia 32 Bit drivers
  when: 
    - multilib_support is succeeded 
    - vendor.stdout.find("NVIDIA") != -1
  become: true
  pacman:
    name: lib32-nvidia-utils

###      INTEL      ###
- name: Install Intel Driver
  when: vendor.stdout.find("Intel") != -1
  become: true
  pacman:
    name: vulkan-intel

- name: Install Intel 32 Bit Driver
  when: 
    - vendor.stdout.find("Intel") != -1
    - multilib_support is succeeded
  become: true
  pacman:
    name: lib32-vulkan-intel
