#SPDX-License-Identifier: MIT-0
---
# tasks file for usb-c-thunderbolt
- name: USB-C udev rule
  become: true
  register: changed_udev_rule
  lineinfile:
    path: /etc/udev/rules.d/99-removable.rules
    create: true
    line: ACTION=="add", SUBSYSTEM=="thunderbolt", ATTR{authorized}=="0", ATTR{authorized}="1"

- name: Reload udev rules
  when: changed_udev_rule is changed
  become: true
  command:
    argv: 
      - udevadm
      - control 
      - --reload

# TODO thunderbolt.host_reset=false (KERNEL PARAMETER)
